### ISSUE TITLE
CI/Github Actions for Ubuntu and MacOS

### ISSUE THREAD

**Issue by MichaelUnknown** [TheLartians/ModernCppStarter#65]
If I am not mistaken, unix and mac (default) build systems are not multi configuration. Thus, your github actions for ubuntu and mac (while still working) might not do what you actually expect them to do. So I think
```yaml
# ubuntu.yaml
    - name: configure
      run: cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1

    - name: build
      run: cmake --build build --config Debug -j4
```
should rather be
```yaml
    - name: configure
      run: cmake -Htest -Bbuild -D ENABLE_TEST_COVERAGE=1 -D CMAKE_BUILD_TYPE=Debug

    - name: build
      run: cmake --build build -j4
```
Any comments?
